### ISSUE TITLE
compile failure on Fedora 26 (libxml2.so.2.9.4)

### ISSUE THREAD

**Issue by jamesrleu** [sjzasada/XML-CanonicalizeXML#1]
[jleu-laptop 26 jleu 4:13pm] ~/clients/XML-CanonicalizeXML-0.5-> perl Makefile.PL 
Checking if your kit is complete...
Looks good
MakeMaker (v7.24)
Potential libraries are '-lxml2 -lz -llzma -lm -ldl':
xml2 not found in /usr/local/lib64
'-lxml2' found at /lib64/libxml2.so.2.9.4
z not found in /usr/local/lib64
'-lz' found at /lib64/libz.so.1.2.11
lzma not found in /usr/local/lib64
'-llzma' found at /lib64/liblzma.so.5.2.3
m not found in /usr/local/lib64
'-lm' found at /lib64/libm.so.6
dl not found in /usr/local/lib64
'-ldl' found at /lib64/libdl.so.2
Warning (non-fatal): Target 'dynamic' depends on targets in skipped section 'dynamic_lib'
Warning (non-fatal): Target 'static' depends on targets in skipped section 'static_lib'
Generating a Unix-style Makefile
Writing Makefile for Mytest2::canon
Writing MYMETA.yml and MYMETA.json
Generating a Unix-style Makefile
Writing Makefile for XML::CanonicalizeXML
Writing MYMETA.yml and MYMETA.json
[jleu-laptop 26 jleu 4:13pm] ~/clients/XML-CanonicalizeXML-0.5-> make
cp lib/XML/CanonicalizeXML.pm blib/lib/XML/CanonicalizeXML.pm
AutoSplitting blib/lib/XML/CanonicalizeXML.pm (blib/lib/auto/XML/CanonicalizeXML)
cd canon && make 
make[1]: Entering directory '/home/jleu/clients/XML-CanonicalizeXML-0.5/canon'
gcc -c  -I. -I/usr/include/libxml2 -D_REENTRANT -D_GNU_SOURCE -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -fwrapv -fno-strict-aliasing -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -g   -DVERSION=\"\" -DXS_VERSION=\"\" -fPIC "-I/usr/lib64/perl5/CORE"   canon.c
canon.c: In function ‘canonicalize’:
canon.c:163:19: warning: pointer targets in passing argument 1 of ‘parse_list’ differ in signedness [-Wpointer-sign]
   list=parse_list(nameSpace);
                   ^~~~~~~~~
canon.c:24:19: note: expected ‘xmlChar * {aka unsigned char *}’ but argument is of type ‘char *’
 static xmlChar ** parse_list(xmlChar *str) {
                   ^~~~~~~~~~
canon.c:179:11: warning: implicit declaration of function ‘xmlC14NDocDumpMemory’; did you mean ‘xmlDocDumpMemory’? [-Wimplicit-function-declaration]
   int i = xmlC14NDocDumpMemory (myXmlDoc,  (xpath) ? xpath->nodesetval : NULL,
           ^~~~~~~~~~~~~~~~~~~~
           xmlDocDumpMemory
ar cr libcanon.a canon.o
: libcanon.a
make[1]: Leaving directory '/home/jleu/clients/XML-CanonicalizeXML-0.5/canon'
make[1]: Entering directory '/home/jleu/clients/XML-CanonicalizeXML-0.5/canon'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/jleu/clients/XML-CanonicalizeXML-0.5/canon'
Running Mkbootstrap for CanonicalizeXML ()
chmod 644 "CanonicalizeXML.bs"
"/usr/bin/perl" -MExtUtils::Command::MM -e 'cp_nonempty' -- CanonicalizeXML.bs blib/arch/auto/XML/CanonicalizeXML/CanonicalizeXML.bs 644
"/usr/bin/perl" "/usr/share/perl5/vendor_perl/ExtUtils/xsubpp"  -typemap '/usr/share/perl5/ExtUtils/typemap'  CanonicalizeXML.xs > CanonicalizeXML.xsc
Please specify prototyping behavior for CanonicalizeXML.xs (see perlxs manual)
mv CanonicalizeXML.xsc CanonicalizeXML.c
gcc -c  -I. -I/usr/include/libxml2 -D_REENTRANT -D_GNU_SOURCE -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -fwrapv -fno-strict-aliasing -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -g   -DVERSION=\"0.05\" -DXS_VERSION=\"0.05\" -fPIC "-I/usr/lib64/perl5/CORE"   CanonicalizeXML.c
In file included from CanonicalizeXML.xs:5:0:
ppport.h:231:0: warning: "PERL_UNUSED_DECL" redefined
 #  define PERL_UNUSED_DECL
 
In file included from CanonicalizeXML.xs:2:0:
/usr/lib64/perl5/CORE/perl.h:313:0: note: this is the location of the previous definition
 #    define PERL_UNUSED_DECL __attribute__unused__
 
In file included from CanonicalizeXML.xs:8:0:
canon/canon.h:2:12: error: conflicting types for ‘canonicalize’
 extern int canonicalize (char *xmlString, char *xpathString, char *nameSpace, int exc, int comm, char *output);
            ^~~~~~~~~~~~
In file included from /usr/include/features.h:410:0,
                 from /usr/include/sys/types.h:25,
                 from /usr/lib64/perl5/CORE/perl.h:689,
                 from CanonicalizeXML.xs:2:
/usr/include/bits/mathcalls.h:435:1: note: previous declaration of ‘canonicalize’ was here
 __MATHDECL_1 (int, canonicalize,, (_Mdouble_ *__cx, const _Mdouble_ *__x));
 ^
In file included from CanonicalizeXML.xs:3:0:
CanonicalizeXML.c: In function ‘XS_XML__CanonicalizeXML_constant’:
/usr/lib64/perl5/CORE/XSUB.h:194:28: warning: unused variable ‘targ’ [-Wunused-variable]
 #define dXSTARG SV * const targ = ((PL_op->op_private & OPpENTERSUB_HASTARG) \
                            ^
./const-xs.inc:5:2: note: in expansion of macro ‘dXSTARG’
  dXSTARG; /* Faster if we have it.  */
  ^~~~~~~
CanonicalizeXML.xs: In function ‘XS_XML__CanonicalizeXML_canonicalize’:
CanonicalizeXML.xs:28:82: warning: passing argument 6 of ‘canonicalize’ from incompatible pointer type [-Wincompatible-pointer-types]
     error = canonicalize(xml,xpath,namespace,exclusive,with_comments,&output);
                                                                      ^
In file included from CanonicalizeXML.xs:8:0:
canon/canon.h:2:12: note: expected ‘char *’ but argument is of type ‘xmlChar ** {aka unsigned char **}’
 extern int canonicalize (char *xmlString, char *xpathString, char *nameSpace, int exc, int comm, char *output);
            ^~~~~~~~~~~~
make: *** [Makefile:341: CanonicalizeXML.o] Error 1

**Comment by sjzasada** [comment]
Thanks for the report. I've updated canon.c to work with newer versions of libxml2 and pushed the [new version](https://github.com/sjzasada/XML-CanonicalizeXML/releases/tag/0.06) to [CPAN](https://metacpan.org/pod/release/SJZASADA/XML-CanonicalizeXML-0.06/lib/XML/CanonicalizeXML.pm). Please test and close the ticket if it works.

**Comment by jamesrleu** [comment]
On Mon, Jan 15, 2018 at 01:12:00PM +0000, Stefan Zasada wrote:
> Thanks for the report. I've updated canon.c to work with newer versions of libxml2 and pushed the new version to CPAN. Please test and close the ticket if it works. 
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/sjzasada/XML-CanonicalizeXML/issues/1#issuecomment-357678873

Thank you for the quick response.

I just tried building and I'm getting a new error.  If it makes a difference I'm building
against a perl 5.18.2 perlbrew env.

Thank you for your time,
James

Unpacking XML-CanonicalizeXML-0.06.tar.gz
OK
XML-CanonicalizeXML-0.06/
XML-CanonicalizeXML-0.06/const-c.inc
XML-CanonicalizeXML-0.06/fallback/
XML-CanonicalizeXML-0.06/Changes
XML-CanonicalizeXML-0.06/MANIFEST
XML-CanonicalizeXML-0.06/const-xs.inc
XML-CanonicalizeXML-0.06/ppport.h
XML-CanonicalizeXML-0.06/t/
XML-CanonicalizeXML-0.06/README
XML-CanonicalizeXML-0.06/canon/
XML-CanonicalizeXML-0.06/META.yml
XML-CanonicalizeXML-0.06/lib/
XML-CanonicalizeXML-0.06/Makefile.PL
XML-CanonicalizeXML-0.06/CanonicalizeXML.xs
XML-CanonicalizeXML-0.06/META.json
XML-CanonicalizeXML-0.06/lib/XML/
XML-CanonicalizeXML-0.06/lib/XML/CanonicalizeXML.pm
XML-CanonicalizeXML-0.06/canon/canon.c
XML-CanonicalizeXML-0.06/canon/canon.h
XML-CanonicalizeXML-0.06/canon/Makefile.PL
XML-CanonicalizeXML-0.06/t/XML-CanonicalizeXML.t
XML-CanonicalizeXML-0.06/fallback/const-c.inc
XML-CanonicalizeXML-0.06/fallback/const-xs.inc
Entering XML-CanonicalizeXML-0.06
Checking configure dependencies from META.json
Checking if you have ExtUtils::MakeMaker 6.58 ... Yes (6.66)
Running Makefile.PL
Configuring XML-CanonicalizeXML-0.06 ... Checking if your kit is complete...
Looks good
Potential libraries are '-lxml2 -lz -llzma -lm -ldl':
MakeMaker (v6.66)
xml2 not found in /usr/local/lib
'-lxml2' found at /lib/../lib64/libxml2.so.2.9.4
z not found in /usr/local/lib
'-lz' found at /lib/../lib64/libz.so.1.2.11
lzma not found in /usr/local/lib
'-llzma' found at /lib/../lib64/liblzma.so.5.2.3
m not found in /usr/local/lib
'-lm' found at /lib/../lib64/libm.so.6
dl not found in /usr/local/lib
'-ldl' found at /lib/../lib64/libdl.so.2
Warning (non-fatal): Target 'dynamic' depends on targets in skipped section 'dynamic_lib'
Warning (non-fatal): Target 'static' depends on targets in skipped section 'static_lib'
Writing Makefile for Mytest2::canon
Writing MYMETA.yml and MYMETA.json
Writing Makefile for XML::CanonicalizeXML
Writing MYMETA.yml and MYMETA.json
Checking dependencies from MYMETA.json ...
Checking if you have ExtUtils::MakeMaker 0 ... Yes (6.66)
OK
Building XML-CanonicalizeXML-0.06 ... cp lib/XML/CanonicalizeXML.pm blib/lib/XML/CanonicalizeXML.pm
AutoSplitting blib/lib/XML/CanonicalizeXML.pm (blib/lib/auto/XML/CanonicalizeXML)
cd canon && make 
make[1]: Entering directory '/home/jleu/.cpanm/work/1516023624.27147/XML-CanonicalizeXML-0.06/canon'
cc -c  -I. -I/usr/include/libxml2 -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -O2   -DVERSION=\"\" -DXS_VERSION=\"\" -fPIC "-I/var/www/sdp/perlbrew/perls/perl-5.18.2/lib/5.18.2/x86_64-linux/CORE"   canon.c
ar cr libcanon.a canon.o
: libcanon.a
make[1]: Leaving directory '/home/jleu/.cpanm/work/1516023624.27147/XML-CanonicalizeXML-0.06/canon'
make[1]: Entering directory '/home/jleu/.cpanm/work/1516023624.27147/XML-CanonicalizeXML-0.06/canon'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/jleu/.cpanm/work/1516023624.27147/XML-CanonicalizeXML-0.06/canon'
/var/www/sdp/perlbrew/perls/perl-5.18.2/bin/perl /var/www/sdp/perlbrew/perls/perl-5.18.2/lib/5.18.2/ExtUtils/xsubpp  -typemap /var/www/sdp/perlbrew/perls/perl-5.18.2/lib/5.18.2/ExtUtils/typemap  CanonicalizeXML.xs > CanonicalizeXML.xsc && mv CanonicalizeXML.xsc CanonicalizeXML.c
Please specify prototyping behavior for CanonicalizeXML.xs (see perlxs manual)
cc -c  -I. -I/usr/include/libxml2 -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -O2   -DVERSION=\"0.06\" -DXS_VERSION=\"0.06\" -fPIC "-I/var/www/sdp/perlbrew/perls/perl-5.18.2/lib/5.18.2/x86_64-linux/CORE"   CanonicalizeXML.c
In file included from CanonicalizeXML.xs:8:0:
canon/canon.h:3:12: error: conflicting types for ‘canonicalize’
 extern int canonicalize (char *xmlString, char *xpathString, char *nameSpace, int exc, int comm, xmlChar **output);
            ^~~~~~~~~~~~
In file included from /usr/include/features.h:410:0,
                 from /usr/include/sys/types.h:25,
                 from /var/www/sdp/perlbrew/perls/perl-5.18.2/lib/5.18.2/x86_64-linux/CORE/perl.h:650,
                 from CanonicalizeXML.xs:2:
/usr/include/bits/mathcalls.h:435:1: note: previous declaration of ‘canonicalize’ was here
 __MATHDECL_1 (int, canonicalize,, (_Mdouble_ *__cx, const _Mdouble_ *__x));
 ^
make: *** [Makefile:340: CanonicalizeXML.o] Error 1
! Installing XML::CanonicalizeXML failed. See /home/jleu/.cpanm/work/1516023624.27147/build.log for details. Retry with --force to force install it.


-- 
James R. Leu
jleu@mindspring.com

**Comment by sjzasada** [comment]
Can you try building the version I just pushed to GitHub?

**Comment by jamesrleu** [comment]
Thank you!

It builds.  just one warning.  Build output below.  I will very
functionality.

[jleu-laptop 26 jleu 8:34am] ~/clients/XML-CanonicalizeXML-> git log
commit faad5fc164123d5b61c3614016caa4241de06165 (HEAD -> master,
origin/master, origin/
EAD)
Author: Stefan Zasada <stef@parkin.local>
Date:   Mon Jan 15 14:22:23 2018 +0000

    Changed canonialize c function call

commit 6ebec491bd860d2b349e1a05e431b5a4b8fd74b6 (tag: 0.06)
Author: Stefan Zasada <stef@parkin.local>
Date:   Mon Jan 15 13:00:33 2018 +0000

    Updated META files

commit ab147a471ccca1d0236f3083e375e19d9b178005
Author: Stefan Zasada <stef@parkin.local>
Date:   Mon Jan 15 12:50:04 2018 +0000

    Updated README

commit 3760a5656576b00a53f681dc36ec4961a9c6e120
[jleu-laptop 26 jleu 8:34am] ~/clients/XML-CanonicalizeXML-> ls
canon/              const-c.inc   lib/         MANIFEST   ppport.h
CanonicalizeXML.xs  const-xs.inc  LICENSE      META.json  README
Changes             fallback/     Makefile.PL  META.yml   t/
[jleu-laptop 26 jleu 8:34am] ~/clients/XML-CanonicalizeXML-> perl
Makefile.PL
Checking if your kit is complete...
Looks good
MakeMaker (v7.24)
Potential libraries are '-lxml2 -lz -llzma -lm -ldl':
xml2 not found in /usr/local/lib64
'-lxml2' found at /lib64/libxml2.so.2.9.4
z not found in /usr/local/lib64
'-lz' found at /lib64/libz.so.1.2.11
lzma not found in /usr/local/lib64
'-llzma' found at /lib64/liblzma.so.5.2.3
m not found in /usr/local/lib64
'-lm' found at /lib64/libm.so.6
dl not found in /usr/local/lib64
'-ldl' found at /lib64/libdl.so.2
Warning (non-fatal): Target 'dynamic' depends on targets in skipped section
'dynamic_li
'
Warning (non-fatal): Target 'static' depends on targets in skipped section
'static_lib'
Generating a Unix-style Makefile
Writing Makefile for Mytest2::canon
Writing MYMETA.yml and MYMETA.json
Generating a Unix-style Makefile
Writing Makefile for XML::CanonicalizeXML
Writing MYMETA.yml and MYMETA.json
[jleu-laptop 26 jleu 8:34am] ~/clients/XML-CanonicalizeXML-> make
cp lib/XML/CanonicalizeXML.pm blib/lib/XML/CanonicalizeXML.pm
AutoSplitting blib/lib/XML/CanonicalizeXML.pm
(blib/lib/auto/XML/CanonicalizeXML)
cd canon && make
make[1]: Entering directory '/home/jleu/clients/XML-CanonicalizeXML/canon'
gcc -c  -I. -I/usr/include/libxml2 -D_REENTRANT -D_GNU_SOURCE -O2 -g -pipe
-Wall -Werro
=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions
-fstack-protector-strong --param=
sp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -fwrapv
-fno-strict-aliasing
-I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -g
 -DVERSION=\"\" -DX
_VERSION=\"\" -fPIC "-I/usr/lib64/perl5/CORE"   canon.c
ar cr libcanon.a canon.o
: libcanon.a
make[1]: Leaving directory '/home/jleu/clients/XML-CanonicalizeXML/canon'
make[1]: Entering directory '/home/jleu/clients/XML-CanonicalizeXML/canon'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/jleu/clients/XML-CanonicalizeXML/canon'
Running Mkbootstrap for CanonicalizeXML ()
chmod 644 "CanonicalizeXML.bs"
"/usr/bin/perl" -MExtUtils::Command::MM -e 'cp_nonempty' --
CanonicalizeXML.bs blib/arc
/auto/XML/CanonicalizeXML/CanonicalizeXML.bs 644
"/usr/bin/perl" "/usr/share/perl5/vendor_perl/ExtUtils/xsubpp"  -typemap
'/usr/share/pe
l5/ExtUtils/typemap'  CanonicalizeXML.xs > CanonicalizeXML.xsc
Please specify prototyping behavior for CanonicalizeXML.xs (see perlxs
manual)
mv CanonicalizeXML.xsc CanonicalizeXML.c
gcc -c  -I. -I/usr/include/libxml2 -D_REENTRANT -D_GNU_SOURCE -O2 -g -pipe
-Wall -Werro
=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions
-fstack-protector-strong --param=
sp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -fwrapv
-fno-strict-aliasing
-I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -g
 -DVERSION=\"0.07\"
-DXS_VERSION=\"0.07\" -fPIC "-I/usr/lib64/perl5/CORE"   CanonicalizeXML.c
In file included from CanonicalizeXML.xs:3:0:
CanonicalizeXML.c: In function ‘XS_XML__CanonicalizeXML_constant’:
/usr/lib64/perl5/CORE/XSUB.h:194:28: warning: unused variable ‘targ’
[-Wunused-variable
 #define dXSTARG SV * const targ = ((PL_op->op_private &
OPpENTERSUB_HASTARG) \
                            ^
./const-xs.inc:5:2: note: in expansion of macro ‘dXSTARG’
  dXSTARG; /* Faster if we have it.  */
  ^~~~~~~
rm -f blib/arch/auto/XML/CanonicalizeXML/CanonicalizeXML.so
gcc  -shared -Wl,-z,relro  -L/usr/local/lib -fstack-protector-strong
CanonicalizeXML.o
-o blib/arch/auto/XML/CanonicalizeXML/CanonicalizeXML.so canon/libcanon.a \
   -lxml2 -lz -llzma -lm -ldl -lperl   \

chmod 755 blib/arch/auto/XML/CanonicalizeXML/CanonicalizeXML.so
Manifying 1 pod document
[jleu-laptop 26 jleu 8:35am] ~/clients/XML-CanonicalizeXML->

**Comment by sjzasada** [comment]
No problem. Let me know if your tests work (e.g. run `make test`). If it's ok I'll push an updated version to CPAN.

**Comment by jamesrleu** [comment]
all test successful!  Thanks again for your quick response!
